# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bragfile < Formula
  desc "Local-first Go CLI to capture and retrieve career-worthy moments."
  homepage "https://github.com/jysf/bragfile000"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jysf/bragfile000/releases/download/v0.5.2/bragfile000_0.5.2_darwin_amd64.tar.gz"
      sha256 "4eb19c9d199fd8c25fe0ea6473048fa005aba21f605ff80e6dc27d2ec95d3cb1"

      define_method(:install) do
        bin.install "brag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jysf/bragfile000/releases/download/v0.5.2/bragfile000_0.5.2_darwin_arm64.tar.gz"
      sha256 "5d2d90aefe79db465f157e3ddcacdbaa349c696b40977cdbfec7c8427e48949a"

      define_method(:install) do
        bin.install "brag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jysf/bragfile000/releases/download/v0.5.2/bragfile000_0.5.2_linux_amd64.tar.gz"
      sha256 "76b0d36536e409771639c0a5f3c0dcf557d4acd9f0147171ab72be9397aca1f0"
      define_method(:install) do
        bin.install "brag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jysf/bragfile000/releases/download/v0.5.2/bragfile000_0.5.2_linux_arm64.tar.gz"
      sha256 "67b9fd18cc95ae7f7ead887d1798df155b7a28706f8053253872a3126bb1a2aa"
      define_method(:install) do
        bin.install "brag"
      end
    end
  end

  test do
    system "#{bin}/brag", "--version"
  end
end
