# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bragfile < Formula
  desc "Local-first Go CLI to capture and retrieve career-worthy moments."
  homepage "https://github.com/jysf/bragfile000"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jysf/bragfile000/releases/download/v0.6.0/bragfile000_0.6.0_darwin_amd64.tar.gz"
      sha256 "113bd6d0a2ed5bd843ed39ccd3f3415fbf06589c60af8b74ee4702e7787f7579"

      define_method(:install) do
        bin.install "brag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jysf/bragfile000/releases/download/v0.6.0/bragfile000_0.6.0_darwin_arm64.tar.gz"
      sha256 "14b63c406e1ed598f511814c7419d93680f07d107eea8a7d0c7406065d08453f"

      define_method(:install) do
        bin.install "brag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jysf/bragfile000/releases/download/v0.6.0/bragfile000_0.6.0_linux_amd64.tar.gz"
      sha256 "519a2458019297cf35400707c81be7be46ca37d9680d9e751dcbaf84cbb01bf0"
      define_method(:install) do
        bin.install "brag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jysf/bragfile000/releases/download/v0.6.0/bragfile000_0.6.0_linux_arm64.tar.gz"
      sha256 "7ff52923bf45c9f622923e2cb5eff3af3b3b20770d55a65f2dabb292865a98d6"
      define_method(:install) do
        bin.install "brag"
      end
    end
  end

  test do
    system "#{bin}/brag", "--version"
  end
end
